### ISSUE TITLE
Retard? Really?

### ISSUE THREAD

**Issue by robotmachine** [tomdionysus/foaas#107]
It seems rather odd that I have to bring up the fact that calling someone a retard or fucktard is uncool. It's a blight on an otherwise wonderful site.

**Comment by jungshadow** [comment]
Wholeheartedly agree with @robotmachine.

**Comment by karenetheridge** [comment]
![whoosh](https://i.imgur.com/Nunye.jpg)

**Comment by v6** [comment]
// , Have you considered what FOAAS stands for? IT'S NOT POLITICALLY CORRECT.

**Comment by jungshadow** [comment]
I'm hoping that there are still clear lines that still wouldn't be crossed (e.g. racism, sexism, bigotry). The project can still be irreverent and humorous without using words that are offensive to various communities.

**Comment by robotmachine** [comment]
Exactly. There is a difference between silly/vulgar/outlandish and being an asshole. Especially, as in this case, toward a group of people who already have it hard enough.

**Comment by tomdionysus** [comment]
PR the removal and ask for votes.

**Comment by robotmachine** [comment]
Thanks, @tomdionysus . I created https://github.com/tomdionysus/foaas/pull/109 for this.

@jungshadow Mind voting? Probably a futile effort, but I'd like to try.

**Comment by theromulans** [comment]
Perhaps, to encourage getting this through, it would be wise to cite some articles or discussion about why this is uncool - I don't think everyone has the same level of awareness in this area.

**Comment by robotmachine** [comment]
When you say "You are being retarded" or "You retard" to me, the sentiment that you are meaning to convey is most likely that I am doing something that you disapprove. The subtext is that I have the capacity to act or behave differently and that I am choosing to act/behave/speak this way. The reason that 'retard' is problematic is that someone who is actually mentally or developmentally disabled is not able to behave any way other than 'retarded'. The sentiment that 'retard' is a bad thing doesn't hurt me on an individual level, but it does hurt others. My mother has been a teacher for many years and my grandmother before her-- and both of them have worked the disabled. There are those who are simply profoundly disabled and are apparently unaware of the world around them, however there are many who desperately want to be part of society and culture and are repeatedly lambasted and put aside. I'll put a name on him. Mark. Mark was one of the kids that I worked with when I was 18 and worked as a substitute teacher for my mom's class. He has Downs Syndrome. He loves making jokes and reading books, but he struggles to accomplish what a typical six year old can do with ease. This whole thread happened because I was thinking of him. He is in to computers and this sort of thing is something that he would find funny because he would be able to understand how to change the names and send little mean jokes back and forth -- but then I imagine him seeing 'retard'. That's it. Call it overly sensitive or emotional or what you will.
@theromulans Sorry for the ramble. It's all I have in me.

**Comment by jungshadow** [comment]
It might help folks here (and those following the conversation on #109) [to read quotes from people who are the most affected by the word](http://www.r-word.org/r-word-effects-of-the-word.aspx). /cc @theromulans @robotmachine

**Comment by robotmachine** [comment]
Thanks, @jungshadow

**Comment by v6** [comment]
// , Although I appreciate your efforts to make this tool less offensive, is it really enough? 

Perhaps the efforts to help the disadvantage shouldn't stop with the "R-Word". 

For instance, I understand that the word "Bastard" can be particularly offensive, especially for one of my cousins' children, who was conceived out of wedlock. 

I understand that many people who are not of the faith prefer not to have to deal with Christian language like "Christmas" in their software. 

On the other hand, many Christians, my close family especially, would take offense to the following section of code: https://github.com/tomdionysus/foaas/blob/master/lib/operations/bus.coffee

Also, several older female members have recently had the sobering experience of going pre-diabetic, and I would STRONGLY prefer not to see their plight made light of in an insult. 

The point I'm trying to make by the above is to show the lengths to which you would need to expand this pull request. 

Hopefully this might also shed some light, not just on FOAAS, but also on "the point" of a certain brand of dark, sarcastic humor.

**Comment by theromulans** [comment]
:+1:

**Comment by robotmachine** [comment]
You're not wrong, Walter. You're just an asshole.

**Comment by karenetheridge** [comment]
![language evolves](https://i.imgur.com/tc6vb.jpg)

**Comment by atomboulian** [comment]
:+1: @karenetheridge :smile:

**Comment by v6** [comment]
// , I'm curious what you think about this: 

https://v.gd/FortTq

https://github.com/opal/opal/issues/941

"The idea has spread that people and groups have a right not to be offended. This may sound innocuous. Politeness is a virtue, after all. But if I have a right not to be offended, that means someone must police what you say about me, or about the things I hold dear, such as my ethnic group, religion, or even political beliefs. Since offence is subjective, the power to police it is both vast and arbitrary."
