### ISSUE TITLE
API limitation

### ISSUE THREAD

**Issue by noblebright** [tomdionysus/foaas#115]
First off,

http://www.foaas.com/awesome/Me

However, I noticed that the result "Fuck diabetes - Me" isn't possible via your API.  I wanted to apply the /:thing/:from endpoint, but it ended up getting the /diabetes/:from endpoint instead.  Consider disambiguating the general /:thing/from case from specific foaas cases..

**Comment by tomdionysus** [comment]
Yes, I've been considering moving /:thing to it's own subroute. Breaking change though, semantic versioning, yada yada.

**Comment by jnawk** [comment]
All new one argument endpoints break the /:thing/:from endpoint as they are added.   Why not add /thing/:thing/:from as a new endpoint, and alter /:thing/:from to send HTTP 301 to /thing/:thing/:from ?

**Comment by peteroreil** [comment]
/%20diabetes/me
