### ISSUE TITLE
/field endpoint inputs seem reversed 

### ISSUE THREAD

**Issue by Dev-iL** [tomdionysus/foaas#118]
I believe `/field/:name/:from/:reference` should be `/field/:from/:name/:reference` and consequently:

'And **:from** said unto **:name**, "Verily, cast thine eyes upon the field in which I grow my fucks", and **:name** gave witness unto the field, and saw that it was barren. - :reference'

**Comment by tomdionysus** [comment]
Good point well made, but there's clients out there which now _rely_ on the fact that it's Broken By Design™. Maybe we'll fix it in the fabled (breaking) 1.0.0 release.

**Comment by Dev-iL** [comment]
This seems somewhat... _unresolved_... Would you perhaps consider either labeling it as "wontfix" or adding it to the "1.0.0" milestone...?
