### ISSUE TITLE
MyMemory quota depleted

### ISSUE THREAD

**Issue by maxicecilia** [tomdionysus/foaas#120]
Trying to use the ?i18n option I got this error message:

> MYMEMORY WARNING: YOU USED ALL AVAILABLE FREE TRANSLATIONS FOR TODAY. VISIT HTTP://MYMEMORY.TRANSLATED.NET/DOC/QUOTAREACHED TO TRANSLATE MORE

I think a simply check it's enough to hide this message and probably return the non-translated response? I'll try to make some time to push a PR.

btw, awesome work/

**Comment by tomdionysus** [comment]
Yeah, translated.net has a quota. I'll speak to them to see if we can get it bumped up. I'm massively pleased that people like foaas, but I'm not up for paying Large Sums Of Cash monthly just so the IT sector can have a giggle.

Handling the error better would be a plus though, PR welcome.
