### ISSUE TITLE
_Alias_ /stfu/:name/:from to /shutup/:name/:from

### ISSUE THREAD

**Issue by steadweb** [tomdionysus/foaas#124]
Because STFU is well known. 

Could either `deprecate and replace` or `alias`. Former would require a major version bump, though.

**Comment by tomdionysus** [comment]
Alias for now, PR? 

Brace Yourself: `v1.0.0` is coming.

**Comment by tomdionysus** [comment]
Any PR for the alias?

**Comment by steadweb** [comment]
I can add one, apologies I haven't responded sooner.
