### ISSUE TITLE
Add "/me/:from" option

### ISSUE THREAD

**Issue by steveholden** [tomdionysus/foaas#126]
Given that an imperative instruction about oneself can be used as an expression of amazement or bewilderment, it might be a useful addition. I'm not sure I'd choose to make a pull request, chicken that I am.

**Comment by tomdionysus** [comment]
Aww go on :) It likes being scratched with PRs, you get the leg going and all...

**Comment by lparkermg** [comment]
Consider it done :D

**Comment by tomdionysus** [comment]
Done in v1.1.0
