### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by hdchan** [tomdionysus/foaas#137]
Should return a Slack outgoingwebhook compatible JSON format to use

**Comment by coldfumonkeh** [comment]
Do you mean formatting the simple JSON response with the 'text' name value pair (https://api.slack.com/outgoing-webhooks) or providing a way to set formatting options for message attachments (https://api.slack.com/docs/attachments)?

**Comment by tomdionysus** [comment]
We're not modifying the base API and breaking a couple of dozen clients just to handle Slack. No reason why a Slack compatible output couldn't be a filter though - should be relatively easy, if someone wants to have a go?
