### ISSUE TITLE
/retard not consistent

### ISSUE THREAD

**Issue by mmatthews1981** [tomdionysus/foaas#140]
why /retard, when it returns "fucktard"? Shouldn't it be consistent?

**Comment by bburket** [comment]
I think 80% of my code review comments can be summarized as this statement

**Comment by tomdionysus** [comment]
I think it was argued / decided that 'retard' was offensive.

**Comment by SSederberg** [comment]
It was (with objections and suggestions to make it less offensive), but no one has gotten around to fix it. 

See #107 and #109

**Comment by aegershman** [comment]
There's a difference between irreverent profanity and being derogatory. I'd recommend removing that endpoint altogether.
