### ISSUE TITLE
json response

### ISSUE THREAD

**Issue by talvasconcelos** [tomdionysus/foaas#154]
hi, i'm trying to get a json response from your api but can only get html. i want to do a funny "f*ck off" postcard website.
maybe i'm not calling the correct endpoint, or i'm missing some headers. at the moment i'm using postman for testing. some help would be nice.

thanks,
tiago

**Comment by petedmarsh** [comment]
Hi tiago,

Setting your Accept header to application/json should do it.

Cheers,

Pete

**Comment by talvasconcelos** [comment]
oh man, i feel so stupid right now... i was using content-type application/json

thanks a lot...
