### ISSUE TITLE
/cool/:name inconsistent

### ISSUE THREAD

**Issue by rikribbers** [tomdionysus/foaas#155]
http://foaas.com/cool/rik returns 'bro' while documentation says 'Bro'

I have forked and fixed both, just let me know which one to create a pull-request from.....

see https://github.com/rikribbers/foaas

**Comment by brettminnie** [comment]
Probably documentation, don't think Bro qualifies as a proper noun

**Comment by rikribbers** [comment]
mhh somehow created a new issue with the pull request... sorry for that...
