### ISSUE TITLE
Translations doesn't handle special characters.

### ISSUE THREAD

**Issue by Spinkelben** [tomdionysus/foaas#199]
This link return 408, from the translater service [http://foaas.com/keepcalm/Keep%20Programming/Søren?i18n=da-dk](http://foaas.com/keepcalm/Keep%20Programming/Søren?i18n=da-dk).

**Comment by tomdionysus** [comment]
Yup, foaas just throws output via mymemory.translated.net. I'm thinking of marking it 'best effort', unless anyone has a better idea for i18n.

**Comment by FurkanKambay** [comment]
@tomdionysus How 'bout real i18n with JSON files for each lang?

**Comment by tomdionysus** [comment]
That would be preferable. But having dozens of operations translated. I'm going to call it for now and reconsider the whole i18n thing.
