### ISSUE TITLE
Strict transport security not enforced

### ISSUE THREAD

**Issue by pencho** [tomdionysus/foaas#202]
Steps to reproduce:  1. Go to http://foaas.com/
Expected behaviour: 301 to https://foaas.com/
Non-encrypted connections should be redirected.

**Comment by ocdtrekkie** [comment]
I find being _forced_ to use HTTPS extremely unpreferable. Though the description URL and readme URL should probably be HTTPS, so that the default when people click a link on the repo is HTTPS.

**Comment by tomdionysus** [comment]
Agree, fixed.
