### ISSUE TITLE
Mistake in  /keep/:name/:from

### ISSUE THREAD

**Issue by MaxVidgof** [tomdionysus/foaas#222]
In /keep/:name/:from, shouldn't it be  ':name **,** F\*ck off. And when you get there...' instead of  ':name: F\*ck off. And when you get there...' ? So, a comma instead of a colon

**Comment by tomdionysus** [comment]
Although I agree with you, I don't think the correction merits changing the API - such a correction could be called pedantic - the endpoint has been in service for some time now and I don't want to risk downstream consumer problems.
