### ISSUE TITLE
API Response

### ISSUE THREAD

**Issue by FeelsBadMan1** [tomdionysus/foaas#252]
Hello, somehow the api not returns json objects but text instead. here is what i did:

request url: https://foaas.com/absolutely/discorduser/a really cool person
response error:     raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://foaas.com/absolutely/discorduser/a%20really%20cool%20person')

**Comment by ilhomidin** [comment]
You miss one field in headers:
`accept`: `application/json`

```python
import requests

requests.get("https://foaas.com/absolutely/discorduser/a").json() # raise similar exception
requests.get("https://foaas.com/absolutely/discorduser/a", headers={"accept": "application/json"}).json() # return valid json
```

**Comment by FeelsBadMan1** [comment]
thank u, That solved the issure i had ;D as of solved now im closing this issue
