### ISSUE TITLE
App down

### ISSUE THREAD

**Issue by bmw2621** [tomdionysus/foaas#261]
Noticed today the app is down and showing a heroku error page.

**Comment by anasarkawi1** [comment]
2 weeks later it seems like the app is still down.

**Comment by TheBlapse** [comment]
Heroku stopped their free tier, that's why perhaps?

**Comment by cluberti** [comment]
Obligatory.

https://www.youtube.com/watch?v=uRGljemfwUE

**Comment by mariansam** [comment]
@tomdionysus You don't plan to run this service anymore? :( Maybe use something like Vercel instead of Heroku?
