### ISSUE TITLE
Fascinating lacks a :name parameter

### ISSUE THREAD

**Issue by autra** [tomdionysus/foaas#29]
We should be able to address someone specifically with "fascinating". This would be useful in irc context, when a lot of people are talking nonsense but not everyone. This would allow to spot precisely who needs to shut the fuck up.

The api could be of the form :

    /fascinating/:name/:from

    Will return content of the form 'Fascinating story :name, in what chapter do you shut the fuck up? - :from'. 

:name could be optional, in which case we don't break existing client.

**Comment by tomdionysus** [comment]
@autra apologies for this but could you re-do your PR after today's refactor, each operation is now in its own file and has its own spec - should be trivial.

**Comment by tomdionysus** [comment]
Going to close this around the 21st if there's no PR forthcoming.
