### ISSUE TITLE
Non RESTful response for what should be 404's

### ISSUE THREAD

**Issue by nichochar** [tomdionysus/foaas#35]
When you type in any url which isn't supported, you land on the homepage! FUCK OFF this is not RESTful =}

You probably should have a 404 page with a "did you mean", or a back to homepage button

**Comment by tomdionysus** [comment]
Going to merge the big refactor today, please resubmit a PR after that.

**Comment by tomdionysus** [comment]
Never mind, did it myself: https://github.com/tomdionysus/foaas/pull/61
