### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by philipmuir** [tomdionysus/foaas#53]
Lets use travis to test & deploy once a PR is merged.

**Comment by tomdionysus** [comment]
That would be sweet. I'm merging the big refactor today, and have specs for the renderers and operations but an actual integration suite would be great.

**Comment by eddelbuettel** [comment]
Simple first steps are pretty easy given a) that R has a baked-in system for simple tests as well as b) support for full-blown unit tests via external packages, and c) we are fully set-up at GitHub via Travis:  though not yet a language supported by Travis, there are hundreds of packages using this.

So what I can do (easily) is add a script in tests/ which will tickly all access points I enumerate, and print the response.  R then diffs this to a pre-recorded set, compares and cries Uncle! if they differ. Which gets us an R CMD check failure, which gets us a Travis failure.   

Sounds good?

**Comment by tomdionysus** [comment]
Sure, that would be good :)

**Comment by eddelbuettel** [comment]
I have a very basic test.  It uses the standard R behaviour to 
- run a file in `tests/`, say `tests/foo.R`
- if a reference output file `tests/foo.Rout.save` is present then the current output and the reference output are compared -- and in case of a difference an error is thrown

It's simple but effective.  The initial commit here is [here](https://github.com/eddelbuettel/rfoaas/commit/e638826186a5a642c34b57eecd14f07d75b5d23a) and I may switch to explicitly comparing 'received' versus 'expected' results on a per-query basis.

**Comment by tomdionysus** [comment]
Thanks to @eddelbuettel

**Comment by eddelbuettel** [comment]
I am actually _right now_ committing a better one, now that I swallowed the pill of #62.

**Comment by eddelbuettel** [comment]
This was just committed:  8e3b32f3bcd52b06c305613ea63df25b6274a36f
