### ISSUE TITLE
Behavior change?

### ISSUE THREAD

**Issue by eddelbuettel** [tomdionysus/foaas#62]
FOAAS used to return text/plain which is something rfoaas relied upon.

Now we get html:

```{.r}
R> library(rfoaas)
R> off("XYZ")                     # manually indenting response block
[1] "<html> <head> <title>FOAAS - Fuck off, XYZ. - - edd</title> <meta charset=\"utf-8\"> 
<link href=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\"
 rel=\"stylesheet\"> </head> <body style=\"margin-top:40px;\"> <div class=\"container\"> 
<div id=\"view-10\" view=\"\"><div class=\"hero-unit\"> <h1>Fuck off, XYZ.</h1> 
<p><em>- edd</em></p> </div> </div> </div> 
<script>!function(a,b,c,d,e,f,g){a.GoogleAnalyticsObject=e,a[e]=a[e]||function(){(a[e].q=
a[e].q||[]).push(arguments)},a[e].l=1*new Date,f=b.createElement(c),
g=b.getElementsByTagName(c)[0],f.async=1,
f.src=d,g.parentNode.insertBefore(f,g)}(
window,document,\"script\",\"//www.google-analytics.com/analytics.js\",\"ga\"),
ga(\"create\",\"UA-42551488-1\",\"herokuapp.com\"),ga(\"send\",\"pageview\");
</script> </body> </html>"
R> 
```

I presume I can code around it, but it would be nice not to force every client to do do.

**Comment by eddelbuettel** [comment]
I now think this is a bug as even when I set Accept: headers I unconditionally get html:

```{.r}
R> GET("http://foaas.herokuapp.com/from/you/me", add_headers(Accept="text/plain"))
Response [http://foaas.herokuapp.com/from/you/me]
  Date: 2015-01-03 08:34
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 9.26 kB
<html>
  <head>
    <title>Fuck Off As A Service (FOAAS)</title>

    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  </head>

  <body style="">
    <div class="container">
      <div class="hero-unit">
...
R> GET("http://foaas.herokuapp.com/from/you/me", add_headers(Accept="application/json"))
Response [http://foaas.herokuapp.com/from/you/me]
  Date: 2015-01-03 08:35
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 9.26 kB
<html>
  <head>
    <title>Fuck Off As A Service (FOAAS)</title>

    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  </head>

  <body style="">
    <div class="container">
      <div class="hero-unit">
...
R> 
```

**Comment by tomdionysus** [comment]
Hmm. This is an artefact of the new Accept processing which is handled by express, i.e. the new code doesn't have a lot of fine grained control over what renderer is used by default:

```
  output: (req, res, message, subtitle) =>
    mime = req.accepts(@formatsArray)

    unless mime?
      res.status 406
      res.end()
      return

    @formats[mime](res, message, subtitle)
    res.end()
```
 Arguably if you really want a `text/plain` response you Should™ ask for it, but I can appreciate that it's annoying from the existing rfoaas client perspective. Thoughts? @philipmuir @xenph @maetl @grahamjenson

**Comment by grahamjenson** [comment]
Does this mean that by default the R client asks for html? If that is the case then the R client should be changed to default ask for text. 

Otherwise, if express when given no explicit mime type might just assume html, manually checking the header on the request might be the only way.

**Comment by eddelbuettel** [comment]
The old behaviour was "don't ask don't tell". 

As shown above, I used R's built-in (and simple) `url()` reader -- which _does not allow setting of additional headers_ got plain text back.  Which I then returned to the caller.   That was simple, clean and worked with minimal dependencies.

Right now I am forced to use a heavier http client with _much more dependencies_ just so that I can request text/plain to get what I had before.  [ I now have an option of also returning json and presumably xml which is nice in theory. In practice nobody asked for this. ]

I can live with the change, but I dislike its accidental and undocumented rollout.

**Comment by graymalkin** [comment]
+1 @eddelbuettel 

It's mostly annoying. I have some code I now need to go in and change, because I was using the default behaviour of `text/plain` for the responses. 

It could (should™?) be argued that this is incorrect, but again -- behaviour changes which aren't documented are annoying.

**Comment by eddelbuettel** [comment]
+1 @graymalkin 

I think we should revert FOAAS to the old behaviour, "Published interfaces" are a contract, breaking that is not tasteful.   

I am all for *optionally* extending it, offering richer interfaces etc pp *in addition* to existing ones.

**Comment by graymalkin** [comment]
I don't think the default behaviour is published, is it? It makes no claims as to what will happen by default.

It's like undefined behaviour in C, so I'm not going to go so far as to say that this change is wrong. It's just somewhat annoying.

**Comment by grahamjenson** [comment]
@eddelbuettel: Published interfaces are not contracts in alpha software, foass is only on version "0.0.5" after all. If foass is a service on the internet, default behaviour should be to return json, not html or text.

**Comment by eddelbuettel** [comment]
@grahamjenson Let's agree to disagree here.  

Once proudly list half a dozen client packages on your main page, you entered a contract in not blindly breaking them.

**Comment by graymalkin** [comment]
@eddelbuettel I'm gonna have to start more strongly disagreeing with you, now.

The *default* response type is very much not part of the contract. The documentation doesn't say anything about defaults.

It's not part of the contract if it's not written down, that's not how contracts work.

**Comment by eddelbuettel** [comment]
@graymalkin You are missing my point.  "Behaviour is a contract."  

You keep insisting that I claim something that is not in the docs. Re-read what I wrote; I doubt I ever made that claim. As we all know, real programmers don't write documentation or specs.

This is all implicit, which is why I wrote about **trust**.   But I am bored by this now, so over and out.

**Comment by grahamjenson** [comment]
@eddelbuettel If behaviour is a contract that means that bugs are in the contract, which is clearly wrong.

**Comment by graymalkin** [comment]
@eddelbuettel You're wrong then. A protocol or API is only a contract as far as is documented. If a behaviour is undocumented it isn't something that can or should be relied on.

**Comment by tomdionysus** [comment]
The intention was to extend existing functionality, not to change the behaviour - the service responding with HTML when no Accept header value was sent was an unintended side effect. Looking through everything, if there's no Accept header, we should probably be returning a `406 Not Acceptable` with an associated list (JSON?) of the MIME types supported.

@eddelbuettel although I very much appreciate your support and input with rfoaas and most especially the helpful integration tests as part of your own project, I'd remind you that FOAAS is not a dedicated service to support your specific client. The refactor had to happen given the unwieldy size of the operations code, JSON and XML were indeed requested (and PRd) by other contributors, and to be honest, your dependency problems in your implementation have nothing to do with FOAAS. On the other hand the unexpected change in behaviour _was_ - and for what it's worth you have my apologies, especially given we'd probably never have known without your integration tests.

I move that we implement `406 Not Acceptable`, I shall supply a PR after some rework in My Copious Free Time.

**Comment by eddelbuettel** [comment]
@tomdionysus I appreciate that you took the time to reply with something thoughtful, lifting the debate from the barely-above-total-nonsense level it had reached.  Foaas had stated from the beginning that there could be four responses.  Text/plain was the first listed, and for over a year that was the response.

Changing that was A. Very. Bad. Idea. Indeed.

But your explanation is fine.  Code refactoring happens, and you have yourself a better backend architecture now, and we all move on.  Shame is on all of us for not having tested the contracts we operated under -- but we're now getting there as per #53.

For rfoaas, this means that it moved from package of a few KB of code---an no dependencies---to a package that is still as small, but pulls in a rat's tail of depends to that I can use `httr::GET()`.  In practice that is not a real issue as R installations themselves are not all that tiny ...  

And having httr in the mix means that I could now offer JSON or, #deity forbid, XML in return as well.  Ain't that grand.

**Comment by tomdionysus** [comment]
Thanks @eddelbuettel. http://foaas.com/XML/Everyone - but I couldn't sufficiently troll some old .NET colleagues without it. Maybe FOAAS should have a WSDL.. or maybe I should have a beer instead... hmm... beer :beer:

**Comment by rthbound** [comment]
+1 :beers:
