### ISSUE TITLE
parameters do not match docs for /field/:name/:from/:reference

### ISSUE THREAD

**Issue by yaauie** [tomdionysus/foaas#63]
Docs say:
> # /field/:name/:from/:reference
> Will return content of the form 'And :from said unto :name, "Verily, cast thine eyes upon the field in which I grow my fucks", and :name gave witness unto the field, and saw that it was barren. - :reference'

But `:from` and `:name` are reversed in the response.
~~~
╭─{ yaauie @ beorn in ~ }
╰─○ curl -H 'Accept: text/plain' http://foaas.com/field/:name/:from/:reference
And :name said unto :from, 'Verily, cast thine eyes upon the field in which I grow my fucks', and :from gave witness unto the field, and saw that it was barren. - :reference%
[success]
~~~

**Comment by tomdionysus** [comment]
Well spotted: https://github.com/tomdionysus/foaas/pull/65

**Comment by tomdionysus** [comment]
Fixed and closing.
