### ISSUE TITLE
/you/:name/:from seems to have disappeared

### ISSUE THREAD

**Issue by eddelbuettel** [tomdionysus/foaas#64]
There is nothing here:

```{sh}
edd@max:~/git/foaas(master)$ git pull --all  
Fetching origin
Fetching parentrepo
Already up-to-date.
edd@max:~/git/foaas(master)$ git merge parentrepo/master 
Already up-to-date.
edd@max:~/git/foaas(master)$ find . -name \*you\*
edd@max:~/git/foaas(master)$ 
```

And hitting the URL redirects to the main page.  Yet the docs still have

> you/:name/:from
> Will return content of the form 'Fuck you, :name. - :from', e.g. /you/Tom/Chris will return 'Fuck you, Tom - Chris'

**Comment by tomdionysus** [comment]
Wow. So forget. Much embarrassing. https://github.com/tomdionysus/foaas/pull/66

**Comment by eddelbuettel** [comment]
It would appears that you fixed this without ack'ing it here. 

Closing now.
