### ISSUE TITLE
/random/ endpoint

### ISSUE THREAD

**Issue by zfjagann** [tomdionysus/foaas#84]
I frequently use foaas.com but find it difficult to select an endpoint from the many endpoints available.

It might be nice to add a `/random/:foo/:bar` endpoint that would select a random action and apply it, producing different results each time.

I can hack on a PR for this when I get time, just posting this here incase someone else might find this useful in the mean-time.

**Comment by SwooshyCueb** [comment]
YES PLEASE

**Comment by brettminnie** [comment]
:+1:

On Mon, May 18, 2015 at 10:47 PM, Markus Kitsinger <notifications@github.com

**Comment by dertuxmalwieder** [comment]
Remember to leave out the "positive" fuck-offs as described in #90 though.

**Comment by tomdionysus** [comment]
Implement a flag in the operations so they can be excluded from random selection?

```

module.exports =
  name: "Xmas"
  url: '/xmas/:name/:from'
  excludeFromRandom: true
  ...
```

**Comment by dertuxmalwieder** [comment]
I'd second that.

**Comment by zfjagann** [comment]
@tomdionysus :+1:

**Comment by rodrigouroz** [comment]
Hey guys

I submitted this PR: https://github.com/tomdionysus/foaas/pull/98

Let me know if you like it.
