### ISSUE TITLE
Some fuck-offs are not fuck-offs at all

### ISSUE THREAD

**Issue by dertuxmalwieder** [tomdionysus/foaas#90]
Let me quote the mission statement:

> FOAAS (Fuck Off As A Service) provides a modern, RESTful, scalable solution to the common problem of telling people to fuck off.

According to this very definition, please remove "xmas", "life", and "awesome", as they're probably solving a different problem and are not actually suitable for telling people to fuck off.

**Comment by AnUnknownMiner** [comment]
:-1: 
 Mission Statement != Guideline to follow. 

It doesn't hurt to have some extra operations that doesn't relate to fucking off people, it does help expand on different retorts, and removing said operations (to me and I'm sure other devs) is a waste of time, and removing said operations ~~shouldn't be~~ isn't necessary.

**Comment by dertuxmalwieder** [comment]
Undoing things which already were a waste of time is probably saving some time later. Guess what happens once you add the random function - it will be a bug to have them then.

**Comment by tomdionysus** [comment]
I'm not keen to start removing functionality which clients depend on, please see my comment in https://github.com/tomdionysus/foaas/issues/84 regarding random exclusion.

**Comment by v6** [comment]
// , Well, a lot of new features does mean making the service more complicated.
